name       : python-tomlkit
version    : 0.11.6
release    : 2
source     :
    - https://files.pythonhosted.org/packages/source/t/tomlkit/tomlkit-0.11.6.tar.gz : 71b952e5721688937fb02cf9d354dbcf0785066149d2855e44531ebdd2b65d73
homepage   : https://github.com/sdispater/tomlkit
license    : MIT
component  : programming.python
summary    : Style-preserving TOML library for Python
description: |
    TOML Kit is a 1.0.0-compliant TOML library. It includes a parser that preserves all comments, indentations, whitespace and internal element ordering, and makes them accessible and editable via an intuitive API.
builddeps  :
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
