name       : python-tomlkit
version    : 0.11.4
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/t/tomlkit/tomlkit-0.11.4.tar.gz : 3235a9010fae54323e727c3ac06fb720752fe6635b3426e379daec60fbd44a83
homepage   : https://github.com/sdispater/tomlkit
license    : MIT
component  : programming.python
summary    : Style-preserving TOML library for Python
description: |
    TOML Kit is a 1.0.0-compliant TOML library. It includes a parser that preserves all comments, indentations, whitespace and internal element ordering, and makes them accessible and editable via an intuitive API.
builddeps  :
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
